name: Documentation Issue
description: Describe the need for documentation change
labels: 
  - kind/documentation
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
