/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.robolaunch.model.kubernetes;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * V1CloudRobotSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-07T10:01:23.177Z[Etc/UTC]")
public class V1CloudRobotSpec {
  public static final String SERIALIZED_NAME_CRON_SPEC = "cronSpec";
  @SerializedName(SERIALIZED_NAME_CRON_SPEC)
  private String cronSpec;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public V1CloudRobotSpec cronSpec(String cronSpec) {

    this.cronSpec = cronSpec;
    return this;
  }

  /**
   * Get cronSpec
   * 
   * @return cronSpec
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCronSpec() {
    return cronSpec;
  }

  public void setCronSpec(String cronSpec) {
    this.cronSpec = cronSpec;
  }

  public V1CloudRobotSpec image(String image) {

    this.image = image;
    return this;
  }

  /**
   * Get image
   * 
   * @return image
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public V1CloudRobotSpec replicas(Integer replicas) {

    this.replicas = replicas;
    return this;
  }

  /**
   * Get replicas
   * 
   * @return replicas
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReplicas() {
    return replicas;
  }

  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1CloudRobotSpec v1CloudRobotSpec = (V1CloudRobotSpec) o;
    return Objects.equals(this.cronSpec, v1CloudRobotSpec.cronSpec) &&
        Objects.equals(this.image, v1CloudRobotSpec.image) &&
        Objects.equals(this.replicas, v1CloudRobotSpec.replicas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cronSpec, image, replicas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1CloudRobotSpec {\n");
    sb.append("    cronSpec: ").append(toIndentedString(cronSpec)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
